config/routes.rb
Rails.application.routes.draw do

  resources :articles

# 　root 'articles#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    # 上の行はインスタンスを作っただけ。saveメソッドで保存しないと、消える。
    @article.save
    # 処理の後はindex画面を表示
    redirect_to articles_path
  end


  private
  def article_params
      params.require(:article).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>記事一覧</h1>
<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>
<a href="<%= new_article_path %>">登録する</a>

app/views/articles/new.html.erb
<h1>記事登録フォーム</h1>
<%= form_with model: @article, local: true do |form| %>

<p>
  論文タイトル<br>
  <%= form.text_field :title %>
</p>
<p>
  本文<br>
  <%= form.text_area :body %>
</p>
<%= form.submit "登録" %>
<% end %>

app/views/articles/show.html.erb
<h1>記事詳細</h1>

<p>
  <b>タイトル：<%= @article.title %></b>
</p>
<p>
  <b><%= @article.body %></b>
</p>

<a href="<%= articles_path %>">一覧へ戻る</a>

app/views/articles/view.html.erb
<h1>Articles#view</h1>
<p>Find me in app/views/articles/view.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>